### PR TITLE
Confirmation Screen after submitting a tx

### PR DESCRIPTION
**Pull request by schmanu**
The new screen consists of two elements
* confirmation message containing the nonce of the created tx and the number of batched txs
* button to create a new tx which resets the CSV Form

Screenshot:
Screenshot 2022-04-22 at 14-38-42 Gnosis Safe

issue #404

### CODE REVIEW

**Review by bh2smith — APPROVED** [review]
Seems good, but shouldn't this confirmation screen appear as a popup wizard instead of overwriting the entire App screen?

**Comment by schmanu** [comment]
I thought about it and chose to do it like this because the app is not really using modals anywhere else (except for the Help Button).

I could leave the Header and display this instead of the Form / Tables to make it look more embedded in the ui of the app.

**Comment by bh2smith** [comment]
Whatever you prefer!

**Comment by schmanu** [comment]
Wow this PR is old. I added this feature now in #437

**Pull request closed without merging**
