### PR TITLE
make table scrollable and fixed height

### PR DESCRIPTION
**Pull request by schmanu**
Small GUI change with big effect on huge tables.

Tables from https://github.com/gnosis/safe-react-components do not support sticky headers yet. I might open a PR there some time beause Material-UI supports those already and is used there.

So I hacked the CSS for now to make em sticky, fixed height and scrollable.

### CODE REVIEW

**Review by bh2smith — APPROVED** [review]
I'm cool with this if it is better than before. Although I have not tried it out personally.

**Comment by schmanu** [comment]
> I'm cool with this if it is better than before. Although I have not tried it out personally.

Here is a tiny gif showing the improved behavior I think its much much better for big transactions as the submit button is always visible.

scrolling

**Comment by bh2smith** [comment]
My only suggestion at this point would be to show at least 10 or maybe even 20 records by default with the static height of the box.

**Comment by schmanu** [comment]
> My only suggestion at this point would be to show at least 10 or maybe even 20 records by default with the static height of the box. So that many of the "smallish" use cases wouldn't need the scrolling.

done.

**Pull request merged**
